import { useState } from 'react';
import { View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { Screen, Card, Txt, Chip, Button, Progress, Icon, s } from '../components/ui';
import { useDemo } from '../state/DemoProvider';
import { sessions } from '../data/demo';
import { colors as c } from '../design/theme';
const questions=[{q:'Avant de commencer une séance, quel premier geste vous aide à rester concentré·e ?',choices:['Définir un objectif précis','Ouvrir toutes les fiches à la fois','Éviter toute pause'],answer:0,explain:'Un objectif court et précis donne une direction à votre séance.'},{q:'Après une erreur, quelle démarche favorise une révision utile ?',choices:['Passer immédiatement à autre chose','Identifier pourquoi on a hésité','Relire uniquement son score'],answer:1,explain:'Identifier la raison de votre hésitation permet de préparer une consolidation ciblée.'},{q:'Comment vérifier que vous avez compris une notion ?',choices:['Compter les pages lues','Relire sans s’arrêter','La reformuler avec vos propres mots'],answer:2,explain:'La reformulation aide à repérer ce qui est clair et ce qui mérite une nouvelle lecture.'}];
const names:Record<string,string>={questions:'Questions isolées',dossier:'Dossier progressif',lca:'Lecture critique d’article',examen:'Examen blanc',personnalise:'Entraînement personnalisé',consolidation:'Consolidation'};
export default function Session(){const {id,mode,error}=useLocalSearchParams<{id?:string;mode?:string;error?:string}>();const {complete,resolve}=useDemo();const [index,setIndex]=useState(0);const [choice,setChoice]=useState<number|null>(null);const [checked,setChecked]=useState(false);const [score,setScore]=useState(0);const [finished,setFinished]=useState(false);const question=questions[index];const title=mode?names[mode]??'Entraînement':sessions.find(x=>x.id===id)?.title??'Séance de révision';return <Screen title={title} subtitle="Exercice de démonstration · Aucun contenu médical évalué" back><View style={{maxWidth:740,width:'100%',alignSelf:'center',gap:22}}>{finished?<Card><Icon name="checkmark-circle" size={48} color={c.primary}/><Txt size={26} bold>Un petit pas de plus !</Txt><Txt>Vous avez terminé les 3 questions de méthode. Résultat de cette séance : {score}/3.</Txt><Txt color={c.muted}>Ce résultat ne mesure pas votre maîtrise médicale. {error?'La notion est marquée comme revue dans votre carnet.':'Votre séance du jour est mise à jour lorsqu’elle appartient au programme.'}</Txt><Button title={error?'Retrouver mon carnet':'Retour à mon programme'} onPress={()=>router.replace(error?'/errors':'/')}/></Card>:<><View style={s.between}><Txt color={c.muted}>Étape {index+1} sur 3</Txt><Txt size={12}>À votre rythme</Txt></View><Progress value={index/3*100}/><Card>{mode==='dossier'&&<Txt size={13} color={c.primary}>Fil conducteur : organiser une journée de révision.</Txt>}{mode==='lca'&&<Txt size={13} color={c.primary}>Préparation méthodologique à la LCA. Aucun article scientifique n’est utilisé dans cette démo.</Txt>}{mode==='examen'&&<Txt size={13} color={c.primary}>Aperçu du parcours d’examen, sans chronométrage ni notation officielle.</Txt>}<Txt bold size={23}>{question.q}</Txt>{question.choices.map((x,i)=><Chip key={x} label={x} selected={choice===i} onPress={()=>!checked&&setChoice(i)}/>)}{checked&&<View style={{backgroundColor:c.mint,padding:18,borderRadius:14,gap:8}}><Txt bold>{choice===question.answer?'Bien vu !':'Un repère pour la prochaine fois'}</Txt><Txt>{question.explain}</Txt></View>}<Button disabled={choice===null} title={checked?(index===2?'Terminer ma séance':'Question suivante'):'Valider ma réponse'} onPress={()=>{if(!checked){setChecked(true);if(choice===question.answer)setScore(score+1)}else if(index<2){setIndex(index+1);setChoice(null);setChecked(false)}else{if(id&&sessions.some(x=>x.id===id))complete(id);if(error)resolve(error);setFinished(true)}}}/></Card></>}</View></Screen>}
